# Generated by Django 5.1 on 2024-08-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("passport_number", models.CharField(max_length=9)),
                ("passport_expiry_date", models.DateField()),
                ("birthdate", models.DateField()),
                ("country", models.CharField(max_length=30)),
                ("passport_front_image", models.ImageField(upload_to="")),
                ("passport_back_image", models.ImageField(upload_to="")),
                ("face_image", models.ImageField(upload_to="")),
            ],
        ),
    ]
